-- MySQL Script generated by MySQL Workbench
-- 03/04/20 22:16:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `idHorario` INT NOT NULL,
  `E/S` VARCHAR(45) NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modalidad` (
  `idModalidad` INT NOT NULL,
  `Escolarizada` VARCHAR(45) NULL,
  `Ejecutiva` VARCHAR(45) NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idModalidad`, `Horario_idHorario`),
  INDEX `fk_Modalidad_Horario1_idx` (`Horario_idHorario` ASC),
  CONSTRAINT `fk_Modalidad_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `mydb`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `idGrupos` INT NOT NULL,
  `GRUPO` VARCHAR(10) NULL,
  PRIMARY KEY (`idGrupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turno` (
  `idTurno` INT NOT NULL,
  `Matutino` VARCHAR(45) NULL,
  `Vespertino` VARCHAR(45) NULL,
  `Modalidad_idModalidad` INT NOT NULL,
  `Grupos_idGrupos` INT NOT NULL,
  PRIMARY KEY (`idTurno`, `Modalidad_idModalidad`, `Grupos_idGrupos`),
  INDEX `fk_Turno_Modalidad1_idx` (`Modalidad_idModalidad` ASC),
  INDEX `fk_Turno_Grupos1_idx` (`Grupos_idGrupos` ASC),
  CONSTRAINT `fk_Turno_Modalidad1`
    FOREIGN KEY (`Modalidad_idModalidad`)
    REFERENCES `mydb`.`Modalidad` (`idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Grupos1`
    FOREIGN KEY (`Grupos_idGrupos`)
    REFERENCES `mydb`.`Grupos` (`idGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Ape_P` VARCHAR(45) NULL,
  `Ape_M` VARCHAR(45) NULL,
  `Materia_idMateria` INT NOT NULL,
  `Turno_idTurno` INT NOT NULL,
  `Turno_Modalidad_idModalidad` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Materia_idMateria`, `Turno_idTurno`, `Turno_Modalidad_idModalidad`),
  INDEX `fk_Usuario_Materia1_idx` (`Materia_idMateria` ASC),
  INDEX `fk_Usuario_Turno1_idx` (`Turno_idTurno` ASC, `Turno_Modalidad_idModalidad` ASC),
  CONSTRAINT `fk_Usuario_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Turno1`
    FOREIGN KEY (`Turno_idTurno` , `Turno_Modalidad_idModalidad`)
    REFERENCES `mydb`.`Turno` (`idTurno` , `Modalidad_idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL,
  `Puesto` VARCHAR(45) NULL,
  `Matricula` VARCHAR(9) NULL,
  `Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`idRoles`, `Materia_idMateria`),
  INDEX `fk_Roles_Materia1_idx` (`Materia_idMateria` ASC),
  CONSTRAINT `fk_Roles_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrear` (
  `idCarrear` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descrip` TEXT NULL,
  PRIMARY KEY (`idCarrear`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plantel` (
  `idPlantel` INT NOT NULL,
  `Nombre_plantel` VARCHAR(45) NULL,
  `Ubica` TEXT NULL,
  `Modalidad_idModalidad` INT NOT NULL,
  `Modalidad_Horario_idHorario` INT NOT NULL,
  `Grupos_idGrupos` INT NOT NULL,
  PRIMARY KEY (`idPlantel`, `Modalidad_idModalidad`, `Modalidad_Horario_idHorario`, `Grupos_idGrupos`),
  INDEX `fk_Plantel_Modalidad1_idx` (`Modalidad_idModalidad` ASC, `Modalidad_Horario_idHorario` ASC),
  INDEX `fk_Plantel_Grupos1_idx` (`Grupos_idGrupos` ASC),
  CONSTRAINT `fk_Plantel_Modalidad1`
    FOREIGN KEY (`Modalidad_idModalidad` , `Modalidad_Horario_idHorario`)
    REFERENCES `mydb`.`Modalidad` (`idModalidad` , `Horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plantel_Grupos1`
    FOREIGN KEY (`Grupos_idGrupos`)
    REFERENCES `mydb`.`Grupos` (`idGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles_has_Usuario` (
  `Roles_idRoles` INT NOT NULL,
  `Roles_Materia_idMateria` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Roles_idRoles`, `Roles_Materia_idMateria`, `Usuario_idUsuario`, `Usuario_Materia_idMateria`),
  INDEX `fk_Roles_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Materia_idMateria` ASC),
  INDEX `fk_Roles_has_Usuario_Roles1_idx` (`Roles_idRoles` ASC, `Roles_Materia_idMateria` ASC),
  CONSTRAINT `fk_Roles_has_Usuario_Roles1`
    FOREIGN KEY (`Roles_idRoles` , `Roles_Materia_idMateria`)
    REFERENCES `mydb`.`Roles` (`idRoles` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Materia_idMateria`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Roles` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Materia_idMateria` INT NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  `Roles_Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_Materia_idMateria`, `Roles_idRoles`, `Roles_Materia_idMateria`),
  INDEX `fk_Usuario_has_Roles_Roles1_idx` (`Roles_idRoles` ASC, `Roles_Materia_idMateria` ASC),
  INDEX `fk_Usuario_has_Roles_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Materia_idMateria` ASC),
  CONSTRAINT `fk_Usuario_has_Roles_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Materia_idMateria`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Roles_Roles1`
    FOREIGN KEY (`Roles_idRoles` , `Roles_Materia_idMateria`)
    REFERENCES `mydb`.`Roles` (`idRoles` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia_has_Modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia_has_Modalidad` (
  `Materia_idMateria` INT NOT NULL,
  `Modalidad_idModalidad` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Modalidad_idModalidad`),
  INDEX `fk_Materia_has_Modalidad_Modalidad1_idx` (`Modalidad_idModalidad` ASC),
  INDEX `fk_Materia_has_Modalidad_Materia1_idx` (`Materia_idMateria` ASC),
  CONSTRAINT `fk_Materia_has_Modalidad_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Modalidad_Modalidad1`
    FOREIGN KEY (`Modalidad_idModalidad`)
    REFERENCES `mydb`.`Modalidad` (`idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Roles1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Roles1` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Materia_idMateria` INT NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  `Roles_Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_Materia_idMateria`, `Roles_idRoles`, `Roles_Materia_idMateria`),
  INDEX `fk_Usuario_has_Roles1_Roles1_idx` (`Roles_idRoles` ASC, `Roles_Materia_idMateria` ASC),
  INDEX `fk_Usuario_has_Roles1_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Materia_idMateria` ASC),
  CONSTRAINT `fk_Usuario_has_Roles1_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Materia_idMateria`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Roles1_Roles1`
    FOREIGN KEY (`Roles_idRoles` , `Roles_Materia_idMateria`)
    REFERENCES `mydb`.`Roles` (`idRoles` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Modalidad` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Materia_idMateria` INT NOT NULL,
  `Modalidad_idModalidad` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_Materia_idMateria`, `Modalidad_idModalidad`),
  INDEX `fk_Usuario_has_Modalidad_Modalidad1_idx` (`Modalidad_idModalidad` ASC),
  INDEX `fk_Usuario_has_Modalidad_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Materia_idMateria` ASC),
  CONSTRAINT `fk_Usuario_has_Modalidad_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Materia_idMateria`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Materia_idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Modalidad_Modalidad1`
    FOREIGN KEY (`Modalidad_idModalidad`)
    REFERENCES `mydb`.`Modalidad` (`idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantel_has_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plantel_has_Materia` (
  `Plantel_idPlantel` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Plantel_idPlantel`, `Materia_idMateria`),
  INDEX `fk_Plantel_has_Materia_Materia1_idx` (`Materia_idMateria` ASC),
  INDEX `fk_Plantel_has_Materia_Plantel1_idx` (`Plantel_idPlantel` ASC),
  CONSTRAINT `fk_Plantel_has_Materia_Plantel1`
    FOREIGN KEY (`Plantel_idPlantel`)
    REFERENCES `mydb`.`Plantel` (`idPlantel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plantel_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia_has_Carrear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia_has_Carrear` (
  `Materia_idMateria` INT NOT NULL,
  `Carrear_idCarrear` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Carrear_idCarrear`),
  INDEX `fk_Materia_has_Carrear_Carrear1_idx` (`Carrear_idCarrear` ASC),
  INDEX `fk_Materia_has_Carrear_Materia1_idx` (`Materia_idMateria` ASC),
  CONSTRAINT `fk_Materia_has_Carrear_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Carrear_Carrear1`
    FOREIGN KEY (`Carrear_idCarrear`)
    REFERENCES `mydb`.`Carrear` (`idCarrear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plantel_has_Carrear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plantel_has_Carrear` (
  `Plantel_idPlantel` INT NOT NULL,
  `Carrear_idCarrear` INT NOT NULL,
  PRIMARY KEY (`Plantel_idPlantel`, `Carrear_idCarrear`),
  INDEX `fk_Plantel_has_Carrear_Carrear1_idx` (`Carrear_idCarrear` ASC),
  INDEX `fk_Plantel_has_Carrear_Plantel1_idx` (`Plantel_idPlantel` ASC),
  CONSTRAINT `fk_Plantel_has_Carrear_Plantel1`
    FOREIGN KEY (`Plantel_idPlantel`)
    REFERENCES `mydb`.`Plantel` (`idPlantel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plantel_has_Carrear_Carrear1`
    FOREIGN KEY (`Carrear_idCarrear`)
    REFERENCES `mydb`.`Carrear` (`idCarrear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`alumno` (
  `ID_ALUMNO` INT(5) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `APELLIDDOS` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `EDAD` INT(2) NULL DEFAULT NULL,
  `CARRERA` VARCHAR(30) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `CORREO` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`carrera` (
  `ID_CARRERA` INT(5) NULL DEFAULT NULL,
  `CARRERA` VARCHAR(30) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `DURACION` VARCHAR(15) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `N°_ALUMNOS` INT(3) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`personal_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`personal_extra` (
  `ID_PERSONAL` INT(5) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `APELLIDOS` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `PUESTO` VARCHAR(30) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `EDAD` INT(2) NULL DEFAULT NULL,
  `CORREO` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`profesore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`profesore` (
  `ID_PROFESOR` INT(5) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `APELLIDOS` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `EDAD` INT(2) NULL DEFAULT NULL,
  `CARRERA` VARCHAR(30) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL,
  `CEDULA` INT(12) NULL DEFAULT NULL,
  `CORREO` VARCHAR(50) COLLATE 'utf8mb4_spanish2_ci' NULL DEFAULT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
